server:
  port: 8080

spring:
  application:
    name: BookLending
  datasource:
    url: jdbc:postgresql://localhost:5432/booklending
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  jackson:
    serialization:
      indent-output: true

liquibase:
  change-log: classpath:db/changelog/db.changelog-master.yaml
  contexts: development, production
  default-schema: public
  drop-first: false
  enabled: true
  liquibase-schema: public
  liquibase-tablespace: public
  test-rollback-on-update: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  api-docs:
    enabled: true # Enable or disable API docs
    path: /v3/api-docs # Path to access OpenAPI documentation
  swagger-ui:
    path: /swagger-ui.html # Path to access Swagger UI
    enabled: true # Enable or disable Swagger UI
    url: /v3/api-docs # URL to fetch the OpenAPI documentation